CREATE TABLE Users (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(32) NOT NULL UNIQUE,
	Avatar VARCHAR(255),
	Email VARCHAR(64) NOT NULL UNIQUE,
	Password BLOB ,
	JoinDate DATETIME,
	LastOnline DATETIME,
	Nickname VARCHAR(255),
	Description TEXT
);

CREATE TABLE Questions (
	ID INT NOT NULL AUTO_INCREMENT,
	User INT,
	Titile VARCHAR(255) NOT NULL,
	Content MEDIUMTEXT NOT NULL,
	BestAnswer INT,
	Created DATETIME,
	Updated DATETIME,
	Reference TEXT,
	PRIMARY KEY (ID),
	FOREIGN KEY (User) REFERENCES Users (ID),
	FOREIGN KEY (BestAnswer) REFERENCES Answers (ID)
);

CREATE TABLE Answers (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	User INT NOT NULL,
	Question INT NOT NULL,
	Content TEXT NOT NULL,
	Time DATETIME,
	Displayed BOOL DEFAULT FALSE,
	Solved BOOL DEFAULT FALSE,
	FOREIGN KEY (User) REFERENCES Users (ID),
	FOREIGN KEY (Question) REFERENCES Questions (ID)
);

CREATE TABLE Issues (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	User INT NOT NULL,
	Question INT NOT NULL,
	Title VARCHAR(255) NOT NULL,
	Content TEXT NOT NULL,
	Time DATETIME,
	FOREIGN KEY (User) REFERENCES Users (ID),
	FOREIGN KEY (Question) REFERENCES Questions (ID)
);

CREATE TABLE QuestionVotes (
	User INT,
	Question INT,
	Evaluation BOOL NOT NULL DEFAULT 1,
	Time DATETIME , 
	PRIMARY KEY (User, Question),
	FOREIGN KEY (User) REFERENCES Users (ID),
	FOREIGN KEY (Question) REFERENCES Questions (ID)
);


CREATE TABLE AnswerVotes (
	User INT,
	Answer INT,
	Evaluation BOOL NOT NULL DEFAULT 1,
	Time DATETIME , 
	PRIMARY KEY (User, Answer),
	FOREIGN KEY (User) REFERENCES Users (ID),
	FOREIGN KEY (Answer) REFERENCES Answers (ID)
);

CREATE TABLE Sessions (
	ID CHAR(36),
	User INT NOT NULL,
	LastUsed TIMESTAMP NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (User) REFERENCES Users (ID)
);

CREATE TABLE IssueReplies (
        ID INT,
        User INT NOT NULL,
        Issue INT NOT NULL,
        Time DATETIME NOT NULL,
        Content TEXT NOT NULL,
        PRIMARY KEY (ID),
        FOREIGN KEY (User) REFERENCES Users (ID),
        FOREIGN KEY (Issue) REFERENCES Issues (ID)
);


CREATE TABLE AnswerReplies (
	ID INT,
	User INT NOT NULL,
	Answer INT NOT NULL,
	Time DATETIME NOT NULL,
	Content TEXT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (User) REFERENCES Users (ID),
	FOREIGN KEY (Answer) REFERENCES Answers (ID)
);
